// Mocks generated by Mockito 5.4.3 from annotations
// in test_tdd/test/degree_to_angular_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'package:mockito/mockito.dart' as _i1;
import 'package:test_tdd/feature/convertion/converter_util.dart' as _i3;
import 'package:test_tdd/feature/convertion/domain/angular_measure.dart' as _i2;
import 'package:test_tdd/feature/convertion/domain/degree_measure.dart' as _i4;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeAngularMeasure_0 extends _i1.SmartFake
    implements _i2.AngularMeasure {
  _FakeAngularMeasure_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [ConvertUtil].
///
/// See the documentation for Mockito's code generation for more information.
class MockConvertUtil extends _i1.Mock implements _i3.ConvertUtil {
  MockConvertUtil() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.AngularMeasure convertDegreeIntoAngular(
          _i4.DegreeMeasure? degreeMeasure) =>
      (super.noSuchMethod(
        Invocation.method(
          #convertDegreeIntoAngular,
          [degreeMeasure],
        ),
        returnValue: _FakeAngularMeasure_0(
          this,
          Invocation.method(
            #convertDegreeIntoAngular,
            [degreeMeasure],
          ),
        ),
      ) as _i2.AngularMeasure);
}
